global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Laravel App Metrics
  - job_name: 'laravel-app'
    static_configs:
      - targets: ['app:9000']

  # MySQL Metrics
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-primary:3306']

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379']

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
